assert(check(disk.format(TRACE_DISK, TRACE_DISK_SIZE)) == 0)

local fd = check(disk.open("empty.txt"))
assert(check(disk.read(fd, 64)) == "")
assert(check(disk.getPos(fd)) == 0)
assert(check(disk.seek(fd, 100)) == 0)
assert(check(disk.seek(fd, -100)) == 0)
disk.close(fd)

assert(disk.open(string.rep("x", 31)) == errno.ENAMETOOLONG)

fd = check(disk.open("track.txt"))
assert(check(disk.write(fd, "0123456789abcdef")) == 16)
disk.close(fd)

fd = check(disk.open("track.txt"))
assert(check(disk.read(fd, 7)) == "0123456")
assert(check(disk.getPos(fd)) == 7)
assert(check(disk.read(fd, 3)) == "789")
assert(check(disk.getPos(fd)) == 10)
disk.close(fd)

local fd1 = check(disk.open("dup.txt"))
assert(check(disk.write(fd1, "hello world!")) == 12)
local fd2 = check(disk.open("dup.txt"))
assert(check(disk.read(fd2, 5)) == "hello")
assert(check(disk.getPos(fd1)) == 12)
assert(check(disk.getPos(fd2)) == 5)
disk.close(fd1)
disk.close(fd2)

fd = check(disk.open("busy.txt"))
assert(check(disk.write(fd, "busy")) == 4)
assert(disk.remove("busy.txt") == errno.EBUSY)
assert(disk.unmount() == errno.EBUSY)
disk.close(fd)
assert(check(disk.remove("busy.txt")) == 0)

fd = check(disk.open("boundary.txt"))
assert(check(disk.write(fd, string.rep("Z", 500))) == 500)
assert(check(disk.getPos(fd)) == 500)
assert(check(disk.seek(fd, -500)) == 0)
assert(check(disk.read(fd, 3)) == "ZZZ")
disk.close(fd)

assert(check(disk.unmount()) == 0)
